config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :controllers => { :registrations => 'users' }

  devise_scope :users do
    resources :profile, only: [:show, :edit, :update], controller: "profile"
  end

  root to: 'home#index'

  resources :communities do
    resources :supplements
  end

  mount Ckeditor::Engine => '/ckeditor'

  resources :user_attachments

  resources :discussions, only: [:show, :create]

  resources :leader_requests, only: [:create]

  resources :conversations do
    resources :replies, only: [:new, :create], module: :conversation
  end

  resources :memberships, only: [:create, :destroy]
  resources :posts, only: [:create]
end

app/models/community.rb
class Community < ActiveRecord::Base
  has_many :memberships
  has_many :users, through: :memberships
  has_many :discussions
  has_many :supplements

  validates :name, uniqueness: true, presence: true

  #include in model to be searchable
  searchkick suggest: ["name"]

  #include in model for pagination
  paginates_per 100

   def members
    memberships.map do |membership|
      User.find(membership.user_id)
    end
  end

  def include_user?(user)
    user.communities.include?(self)
  end

  def leaders
    members.select { |member| member.title == 'expert' }
  end

  def member_names
    members.map { |member| member.name }
  end

  def recent_members(number_of_members)
    if members.count < number_of_members
      members
    else
      members.last(number_of_members)
    end
  end

  def newest_discussions
    discussions.order("created_at DESC")
  end
end

app/models/membership.rb
class Membership < ActiveRecord::Base
  belongs_to :user
  belongs_to :community

  def self.for(user, community)
    where(user_id: user.id, community_id: community.id).first
  end
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

 has_many :user_attachments
end

app/models/user.rb
class User < ActiveRecord::Base
  default_scope { order('created_at DESC') }
  acts_as_messageable
  # before_action :authenticate_user!
  has_many :roles
  has_many :memberships
  has_many :connections
  has_many :connects, through: :connections
  has_many :inverse_connections, class_name: "Connections", foreign_key: "connection_id"
  has_many :inverse_connects, through: :inverse_connections, source: :user
  has_many :posts
  has_many :discussions

  validates :username, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true


  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_attachments
  accepts_nested_attributes_for :user_attachments

  TITLES = %i[admin, expert]

  def user_roles
    return unless roles.any?
    roles.map(&:name)
  end

  def communities
    memberships.map { |membership| membership.community }
  end

  def is_connected_to?(user)
    connections.map(&:connect_id).include?(user.id)
  end

  def connection_names
    connections.map(&:connect_id).map do |user_id|
      User.find(user_id).name
    end
  end

  #TODO fix .last
  def profile_photo
    profile_photos = user_attachments.where(attachment_type: "profile_photo")
    if profile_photos.last.present?
      profile_photos.last.avatar
    else
      "default-profile-photo.png"
    end
  end

  def cover_photo
    cover_photos = user_attachments.where(attachment_type: "cover_photo")
    if cover_photos.last.present?
      cover_photos.last.avatar
    else
      "default-cover-photo.png"
    end

  end

  def has_location?
    city || state || country
  end

  def joined_at
    created_at.strftime("%m/%d/%Y")
  end

  def name
    name = first_name.present? ? "#{first_name} #{last_name}" : "Anonymous User"
    username.present? ? username : name
  end

  def mailerbox_email(object)
    email
  end

end

app/models/user_attachment.rb
class UserAttachment < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  belongs_to :profiles
  belongs_to :users
end

app/controllers/communities_controller.rb
class CommunitiesController < ApplicationController

  def index
    @membership = Membership.new 
    if params[:query].present?
      @communities = Community.search(params[:query])
    else
      @communities = Community.all.page params[:page]
    end
  end

  def show
    @community = Community.find(params[:id])
    @discussion = Discussion.new
    @supplement = Supplement.new
  end

  def new
    @community = Community.new
  end

  def create
    @community = Community.new(community_params)
    if @community.save
      flash[:success] = "Your community was created successfully."
      redirect_to community_path(@community)
    else
      flash[:error] = "Your community was not created. Please try again."
      redirect_to root_path
    end
  end

  def update
    @community = Community.find(params[:id])
    @community.update_attributes!(community_params)
    if @community.save
      flash[:success] = "Your community was updated successfully."
      redirect_to community_path(@community)
    else
      flash[:error] = "Your community was not updated. Please try again."
      redirect_to root_path
    end

  end

  def edit
    @community = Community.find(params[:id])
  end


  private

  def community_params
    params.require(:community).permit(:name, :description, :name, :description, :created_at, :updated_at, :prevalence , :cause , :diagnosis, :symptom, :diagnostic_test, :treatment, :prognosis, :tip, :expanded_description)
  end

end

app/controllers/leader_requests_controller.rb
class LeaderRequestsController < ApplicationController
  def create
    ::LeaderRequestMailer.new(leader_request_params, current_user).send
    flash[:success] = "Your Request has been submitted."
      redirect_to :back
  end

  private

  def leader_request_params
    params.require(:leader_request).permit(:community_id, :body, :sender_id)
  end
end

app/controllers/memberships_controller.rb
class MembershipsController < ApplicationController
  def create
    @membership = Membership.new(membership_params)
    if @membership.save
      flash[:success] = "You have successfully joined this community."
      redirect_to community_path(membership_params[:community_id])
    else
      flash[:error] = "There was an error. Could not join community, try again."
      redirect_to :back
    end
  end

  def destroy
    @membership = Membership.find(params[:id])
    @membership.destroy!
    redirect_to :back
  end

  private

  def membership_params
    params.permit(:community_id, :user_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @discussion = Discussion.find(post_params[:discussion_id])
    @post = @discussion.posts.build(post_params)

    if @post.save
      redirect_to :back
    else
      redirect_to :back
    end
  end

  private

  def post_params
    params.require(:post).permit(:body, :discussion_id, :user_id)
  end

end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    update_roles(@user) if user_params[:roles].present?
    @user.update_attributes(user_params.except(:roles))

    if @user.save
      flash[:success] = "Your information has been saved"
    else
      flash[:error] = "Your information has not been saved successfully, please try again"
    end

    redirect_to :back
  end

  private

  def update_roles(user)
    user.roles.clear
    role_ids.each do |role_id|
      role = Role.find(role_id)
      user.roles << role
    end
  end

  def role_ids
    @role_ids ||= params[:user][:roles].reject(&:blank?)
  end

  def user_params
    params.require(:user).permit(:bio, :city, :state, :country, :gender, :avatar, :first_name, :last_name, roles:[])
  end
end

app/controllers/user_attachments_controller.rb
class UserAttachmentsController < ApplicationController
  def create
    @user = User.find(user_attachment_params[:user_id])

    user_attachment_params[:avatar].each do |image|
      @user_attachment = @user.user_attachments.create!(:avatar => image, :attachment_type => attachment_type, :user_id => @user.id)
    end

    if @user.save
      flash[:success] = "Your image was saved successfully." 
      redirect_to profile_path(@user)
    else
      flash[:error] = "Your image was not saved successfully. Please try again." 
      redirect_to profile_path(@user)
    end
  end

  private

  def attachment_type
    user_attachment_params[:attachment_type]
  end

  def user_attachment_params
    params.require(:user_attachment).permit(:attachment_type, :user_id, avatar: [])
  end
end

app/views/communities/_community_details.html.haml
%h3.text--teal
  Description
- if @community.expanded_description.present?
  = @community.expanded_description
- else
  = "An expanded description of #{@community.name} has not been added yet."

%h3.text--teal
  Prevalence
- if @community.prevalence.present?
  = @community.prevalence
- else
  = "Prevalence Information of #{@community.name} has not been added yet."

%h3.text--teal
  Causes
- if @community.cause.present?
  = @community.cause
- else
  = "Cause of #{@community.name} have not been added yet."

%h3.text--teal
  Symptoms
- if @community.symptom.present?
  = @community.symptom
- else
  = "Symptoms of #{@community.name} have not been added yet."

%h3.text--teal
  Diagnosis
- if @community.diagnosis.present?
  = @community.diagnosis
- else
  = "Diagnosis of #{@community.name} have not been added yet."

%h3.text--teal
  Diagnostic Test
- if @community.diagnostic_test.present?
  = @community.diagnostic_test
- else
  = "Diagnostic tests of #{@community.name} have not been added yet."

%h3.text--teal
  Treatment
- if @community.treatment.present?
  = @community.treatment
- else
  = "Treatments of #{@community.name} have not been added yet."

%h3.text--teal
  Prognosis
- if @community.prognosis.present?
  = @community.prognosis
- else
  = "Prognosis of #{@community.name} have not been added yet."

%h3.text--teal
  Tips or Suggestions
- if @community.tip.present?
  = @community.tip
- else
  = "Tips or Suggestions of #{@community.name} have not been added yet."

app/views/communities/_community_home.html.haml
%h3
  = "What is #{@community.name}?"

%p
  = @community.description || I18n.t("community.no_description")

.row
  .col-md-8
    %h3
      = I18n.t("community.stats")

    .media
      .media-left
        = image_tag('community-icon.png', class: 'media-object icon-image')
      .media-body.media-middle
        = "#{@community.members.count} community members"

    .media
      .media-left
        = image_tag('discussion-icon.png', class: 'media-object icon-image')
      .media-body.media-middle
        = "#{@community.discussions.count} community discussions"

    .media
      .media-left
        = image_tag('resource-icon.png', class: 'media-object icon-image')
      .media-body.media-middle
        = "#{@community.supplements.count} community resources"

app/views/communities/_community_leaders.html.haml
%h3
  = I18n.t("community.leaders")

- if @community.leaders.present?
  = render partial: "communities/modals/message_leader", locals: { leaders: @community.leaders }
  - @community.leaders.each do |leader|
    .row
      .col-md-3
        .circle
          = image_tag(leader.avatar)
      .col-md-9
        %h4
          = leader.name
        %p
          = leader.bio
        = link_to I18n.t("homepage.commands.send_message"), '#message_leader', data: { target: '#message_leader', toggle: 'modal'}, class: 'btn btn-rareshare'
- else
  %p
    = I18n.t("community.leader_warning")
    - if user_signed_in?
      = link_to I18n.t("community.become_leader"), '#become_leader', data: { target: '#become_leader', toggle: 'modal'}, class: 'btn btn-rareshare'


= render partial: "communities/modals/become_leader"

app/views/communities/_community_members.html.haml
.panel.panel-default
  .panel-heading
    %h3.panel-title
      = I18n.t("community.members")
      .pull-right
        = link_to I18n.t("community.view_all"), memberships_path(community_id: @community.id)
  .panel-body
    .row
      - @community.recent_members(6).each do |member|
        .col-md-4.padding--small--vertical
          = image_tag("default_avatar.png", size: "100x100")
          .text-center
            %strong
              = link_to member.name, profile_path(member)

app/views/communities/_discussions.html.haml
= render partial: "communities/modals/new_discussion"

.panel.panel-default
  .panel-heading
    .pull-right
      = link_to "#new_discussion", { data: { target: '#new_discussion', toggle: 'modal' }, class: 'pull-right' } do
        = fa_icon('plus')
        = "New Discussion"
    .panel-title
      = "Community Discussions"
    
  .panel-body
    - @community.discussions.each do |discussion|
      .media
        .media-left
          = fa_icon 'user 2x'
        .media-body
          %h4.media-heading
            = link_to "#{discussion.title}", discussion_path(discussion)
          .media-body
            = "Subject: #{discussion.subject}"

app/views/communities/_form.html.haml
- content_for(:modal_title) do
  = I18n.t("community.info")

- content_for(:modal_body) do
  = simple_form_for @community, url: community_path(@community) do |f|
    = f.input :disease_information, as: :text
    .modal-footer
      = form_buttons(f, submit_text: "Start Discussion")

#new_disease_info.modal.fade
  = render template: "style_guide/modal"

app/views/communities/_newest_members.html.haml
%h4.text--teal.margin--large--top
  = I18n.t("community.newest_members")
- recent_users(6).each do |user|
  .row.margin--small--bottom
    .col-md-3
      - user_avatar = user.avatar.present? ? user.avatar : "community-icon.png"
      = image_tag user_avatar, class: 'icon-image--rounded'
    .col-md-9{ style: 'margin-top: 15px' }
      = link_to "#{user.name}", profile_path(user)

app/views/communities/_supplements.html.haml
= render partial: "communities/modals/new_supplement"

.panel.panel-default
  .panel-heading
    .pull-right
      - if can? :manage, Community
        = link_to "#new_supplement", { data: { target: '#new_supplement', toggle: 'modal' } } do
          = fa_icon('plus')
          = "Add Resource"
    .panel-title
      = I18n.t("community.resources")
  .panel-body
    %table{width: '100%'}
      %thead
        %th
          = I18n.t("community.title")
        %th
          = I18n.t("community.description")
        %th
          = I18n.t("community.link")
        %th
          = I18n.t("community.date_added")
      %tbody
        - @community.supplements.each do |supplement|
          %tr
            %td
              = supplement.title
            %td
              = supplement.description
            %td
              %a{ href: supplement.link, target: "_blank" }
                = supplement.link
            %td
              = supplement.created_at.strftime("%m/%d/%Y")

app/views/communities/edit.html.haml
.container
  %h4
    ="Community Details"
  .row.margin--medium--bottom
    .col-md-6
      %p
      = simple_form_for @community do |f|
        .form-group
          = f.input :name
          = f.input :description
          = f.input :prevalence
          = f.input :cause
          = f.input :diagnosis
          = f.input :symptom
          = f.input :diagnostic_test
          = f.input :treatment
          = f.input :prognosis
          = f.input :tip
          = f.input :expanded_description

        = f.submit class: 'btn btn-rareshare'

app/views/communities/index.html.haml
.container
  .row
    .col-md-8
      %h3
        = "Communities"
    .col-md-4.margin--small--top
      = form_tag communities_path, class: "form-inline pull-left", method: :get do
        .form-group
          = text_field_tag :query, params[:query], class: "form-control"
          = submit_tag "Search", class: "btn btn-primary"
        - if params[:query].present?
          = link_to "clear", communities_path

  - if current_user.communities.present?
    %h4
      = "My Communities"
    - current_user.communities.sort_by{ |comm| comm.name.downcase}.each do |community|
      .row
        .media
          .media-left
            = image_tag('community-icon.png', class: 'media-object icon-image')
          .media-body.media-middle
            = link_to community.name, community

    %hr.margin--medium

  %h4
    = "All Communities"
  .col-md-10
    %ul.list_group.margin--medium--top
      - @communities.sort_by{ |comm| comm.name.downcase}.each do |community|
        %li.list-group-item.list-group-item--border--horizontal
          = link_to community.name, community
          .pull-right
            - if community.include_user?(current_user)
              = link_to "Leave community", membership_path(Membership.for(current_user, community).id), method: :delete, data: { confirm: "Are you sure you want to leave this community?" }, class: 'btn btn-danger'
            - else
              = button_to 'Join', memberships_path(community_id: community.id, user_id: current_user.id), class: 'btn btn-primary', method: 'post'
          %small
            %p
              = "#{community.members.count} members"
          %p
            - if community.description.present?
              = community.description.truncate(100, separator: ' ')
      = paginate @communities

app/views/communities/show.html.haml
.container
  .row.margin--medium--bottom
    .col-md-9
      %h3
        = @community.name
    .col-md-3
      .row
        .col-md-6
          - if can? :manage, Community
            = link_to "Edit Community", edit_community_path(@community), { class: 'btn btn-default' }
        .col-md-6
          - if @community.include_user?(current_user)
            = link_to "Leave Community", membership_path(Membership.for(current_user, @community).id), method: :delete, data: { confirm: "Are you sure you want to leave this community?" }, class: 'btn btn-danger'
          - else
            = button_to 'Join', memberships_path(community_id: @community.id, user_id: current_user.id), class: 'btn btn-primary', method: 'post'

  %div{:role => "tabpanel"}
    .row
      .col-md-3
        %ul.nav.community-nav{:role => "tablist"}
          %li.active{:role => "presentation"}
            %a{"aria-controls" => "community_home", "data-toggle" => "tab", :href => "#community_home", :role => "tab"} COMMUNITY HOME
          %li{:role => "presentation"}
            %a{"aria-controls" => "community_details", "data-toggle" => "tab", :href => "#community_details", :role => "tab"} COMMUNITY DETAILS
          %li{:role => "presentation"}
            %a{"aria-controls" => "discussion_forum", "data-toggle" => "tab", :href => "#discussion_forum", :role => "tab"} DISCUSSION FORUM
          %li{:role => "presentation"}
            %a{"aria-controls" => "disorder_resources", "data-toggle" => "tab", :href => "#disorder_resources", :role => "tab"} DISORDER RESOURCES
          %li{:role => "presentation"}
            %a{"aria-controls" => "community_leader", "data-toggle" => "tab", :href => "#community_leader", :role => "tab"} COMMUNITY LEADER
          %li{:role => "presentation"}
            = link_to "BACK TO COMMUNITIES LIST", communities_path
      .col-md-9
        .tab-content
          #community_home.tab-pane.active{:role => "tabpanel"}
            = render 'community_home'

          #community_details.tab-pane{:role => "tabpanel"}
            = render 'community_details'

          #discussion_forum.tab-pane{:role => "tabpanel"}
            = render 'discussions/index'

          #disorder_resources.tab-pane{:role => "tabpanel"}
            = render 'supplements'

          #community_leader.tab-pane{:role => "tabpanel"}
            = render partial: 'community_leaders'

          #communities_list.tab-pane{:role => "tabpanel"}
            = link_to communities_path

  %hr

  .row
    .col-md-4.margin--medium--top
      = render partial: 'shared/left_rail_ctas'
    .col-md-8
      .margin--medium--top
        = render partial: 'discussions/summary'

  %hr.margin--medium--top

  = render partial: 'shared/footer_ctas'

app/views/conversations/index.html.haml
%h2
  My Mail
  %ul
  - @conversations.each do |conversation|
    %li
      = conversation.subject
      %p
        -# TODO Refactor please
        = Mailboxer::Message.find(conversation).body
      = link_to I18n.t("form.reply"), new_conversation_reply_path(conversation)

app/views/conversations/replies/new.html.haml
- content_for(:modal_title) do
  = I18n.t("form.reply")

- content_for(:modal_body) do
  = simple_form_for :reply, url: conversation_replies_path(conversation) do |f|
    = f.input :conversation_id, as: :hidden, input_html: { value: conversation.id }
    = f.input :subject, input_html: { value: "Re: #{conversation.subject}", readonly: true }
    = f.input :body, as: :text
    .modal-footer
      = form_buttons(f, submit_text: I18n.t("discussion.start") )

#conversation_reply.modal.fade
  = render template: "style_guide/modal"

app/views/discussions/_blank_state.html.haml
.jumbotron
  .text-center
    = image_tag 'logo.png'
    %h4
      = "#{community.name} community discussions will be posted here."
    %p
      ="There are no new discussions. Start one now!!"

app/views/discussions/_form.html.haml
= simple_form_for :discussion, url: discussions_path do |f|
  = f.input :community_id, as: :hidden, input_html: { value: @community.id }
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  = f.input :title
  = f.input :subject, as: :text, required: false, input_html: { placeholder: "What is this discussion about?" }
  .modal-footer
    = form_buttons(f, submit_text: I18n.t("form.start_discussion") )

app/views/discussions/_index.html.haml
= render partial: "communities/modals/new_discussion"
.margin--small--bottom
  = link_to I18n.t("discussion.new"), "#new_discussion", { data: { target: '#new_discussion', toggle: 'modal' }, class: 'btn btn-primary' }
- if @community.discussions.present?
  .row
    - @community.discussions.order('updated_at DESC').each do |discussion|
      .col-md-1
        - author_image = discussion.author.avatar.present? ? discussion.author.avatar : 'community-icon.png'
        = image_tag author_image, class: 'icon-image--rounded'
      .col-md-11
        %strong
          = link_to "#{discussion.title}", discussion_path(discussion)
        %i
          = "Created by #{discussion.author.name}"
        %br
          %small
            = "Last updated #{time_ago_in_words(discussion.last_updated)} ago"
        %br
        - if discussion.posts.present?
          .row.margin--small--top
            - discussion.newest_posts.take(3).each do |post|
              .col-md-1
                - author_image = post.author.avatar.present? ? post.author.avatar : 'community-icon.png'
                = image_tag author_image, class: 'icon-image--rounded'
              .col-md-11
                %i
                  = I18n.t("homepage.discussion.posted")
                  = link_to post.author.name, profile_path(post.author)
                %br
                %i
                  %small
                    = "#{time_ago_in_words(post.created_at)} ago"
                %p
                  = post.body.html_safe
        = render partial: 'shared/view_full_thread', locals: { discussion: discussion }

- else
  = render partial: 'discussions/blank_state', locals: { community: @community }

app/views/discussions/_summary.html.haml
%h3
  = I18n.t("discussion.title")

.list-group
  - if @community.discussions.present?
    - @community.discussions.order('updated_at DESC').each do |discussion|
      .list-group-item
        %h4.list-group-item-heading
          %strong
            = link_to "#{discussion.title}", discussion_path(discussion)
        %p.list-group-item-text
          = I18n.t("discussion.created")
          %strong
            = link_to "#{discussion.author.name}", profile_path(discussion.author)
          = "Last updated #{discussion.last_updated}"
  - else
    .margin--small--bottom
      = link_to I18n.t("discussion.new"), "#new_discussion", { data: { target: '#new_discussion', toggle: 'modal' }, class: 'btn btn-primary' }
    = render partial: 'discussions/blank_state', locals: { community: @community }

app/views/home/_communities_blank_state.html.haml
.jumbotron
  .text-center
    = image_tag 'logo.png'
    %h4
      = "All your most recent community activity will be posted here once you start using the platform." 
    %p
      ="Please join a community to start using RareShare!!"
    = link_to "Join Now", communities_path, class: 'btn btn-rareshare'

app/views/home/_dashboard.html.haml
.container.margin--medium--top
  - if current_user.communities.present?
    .row.margin--large--top
      .col-md-4
        %h4.border--gray--bottom.text--teal
          = I18n.t("homepage.communities")
        %ul.list-group
          - current_user.communities.each do |community|
            %li.list-group-item.list-group-item--border--bottom
              = link_to community.name, community_path(community)
        = render partial: 'communities/newest_members'
        .margin--medium--top
          = render 'shared/left_rail_ctas'

      .col-md-8
        %h4.text--teal
          = I18n.t("homepage.recent_communities")

        - if current_user.communities.present?
          .row
            - current_user.communities.map(&:newest_discussions).each do |discussions|
              - discussions.each do |discussion|
                .col-md-1
                  - author_image = discussion.author.avatar.present? ? discussion.author.avatar : 'community-icon.png'
                  = image_tag author_image, class: 'icon-image--rounded'
                .col-md-11
                  %strong
                    = link_to "#{discussion.title}", discussion_path(discussion)
                  %i
                    = I18n.t("homepage.discussion.created", author_name: discussion.author.name)
                  %br
                    %small
                      = "Last updated #{time_ago_in_words(discussion.last_updated)} ago"
                  %br
                  %i
                    = "Community: #{discussion.community.name}"
                  - if discussion.posts.present?
                    .row.margin--small--top
                      - discussion.newest_posts.take(3).each do |post|
                        .col-md-1
                          - author_image = post.author.avatar.present? ? post.author.avatar : 'community-icon.png'
                          = image_tag author_image, class: 'icon-image--rounded'
                        .col-md-11
                          %i
                            = I18n.t("homepage.discussion.posted")
                            = link_to post.author.name, profile_path(post.author)
                          %br
                          %i
                            %small
                              = "#{time_ago_in_words(post.created_at)} ago"
                          %p
                            = post.body.html_safe
                  = render partial: 'shared/view_full_thread', locals: { discussion: discussion }

  - else
    = render 'communities_blank_state'

  %hr.margin--medium--top

  = render 'shared/footer_ctas'

app/views/home/_login_form.html.haml
= form_for User.new, as: :user, url: session_path(:user), method: :post, class: 'form-group' do |f|
  .input-group{:style => "margin-bottom: 25px"}
    %span.input-group-addon
      %i.glyphicon.glyphicon-user
    = f.email_field :email, id: "login-email", class: "form-control", placeholder: I18n.t("form.email")

  .input-group{:style => "margin-bottom: 25px"}
    %span.input-group-addon
      %i.glyphicon.glyphicon-lock
    = f.password_field :password, id: "login-password", class: "form-control", placeholder: I18n.t("form.password")

  .form-group
    .controls
      = f.submit I18n.t("form.login"), id: "btn-login", class: "btn btn-rareshare"

app/views/memberships/_form.html.haml
= simple_form_for membership do |f|
  = f.association :community,label_method: :name, prompt: "Please choose a community"
  = f.submit 'Join Community'

app/views/posts/_form.html.haml
= simple_form_for :post, url: posts_path, method: :post do |f|
  = f.input :discussion_id, as: :hidden, input_html: { value: discussion.id }
  = f.input :user_id, as: :hidden, input_html: { value: current_user.id }
  = f.input :body, as: :text, label: false, input_html: { rows: 3, cols: 85, placeholder: "write a reply..." }, :as => :ckeditor, :input_html => { :ckeditor => {:toolbar => 'mini'} }
  = f.submit class: 'btn btn-rareshare'

app/views/shared/_footer_ctas.html.haml
.row.margin--large--vertical
  .col-md-4
    = image_tag('communities.png')
    %h3
      ="Our Communities"
    %p
      = "Join Rare Share to meet other people that have been touched by rare diseases. Learn, engage, and grow with our communities."
    = link_to 'FIND YOUR COMMUNITY', communities_path, class: 'btn btn-rareshare'
  .col-md-4
    = image_tag('physicians.png')
    %h3
      ="Our Physicians"
    %p
      = "Our growing team of volunteer physicians are here to inform you of the new breakthroughs in science."
    = link_to 'MEET THE SPECIALISTS', '#', class: 'btn btn-rareshare'
  .col-md-4
    = image_tag('leaders.png')
    %h3
      ="Our Community Leaders"
    %p
      = "Community leaders are active users that have been touched by the rare disease that they are a part of. Not only are they there to help facilitate conversations and provide new information that is relevant for the group, but they are there for you and to let you know you have a support system on Rare Share."
    = link_to 'MEET THE LEADERS', '#', class: 'btn btn-rareshare'

app/views/shared/_header.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#rareshare-navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        -3.times do
          %span.icon-bar
      %a.navbar-brand{:href => root_path}
        = image_tag 'logo.png'
    .collapse.navbar-collapse#rareshare-navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            %ul.nav.navbar-nav.navbar-right
              %li
                = link_to 'Communities', communities_path
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Account
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                = link_to "My Profile", profile_path(current_user)
              %li.divider
              %li
                = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %ul.nav.navbar-nav
            %li
              = link_to I18n.t("navigation.sign_in").upcase, new_user_session_path
            %li
              = link_to I18n.t("navigation.register").upcase, new_user_registration_path

app/views/shared/_view_full_thread.html.haml
.border--gray--bottom.margin--small--vertical
  = link_to I18n.t("homepage.discussion.thread"), discussion_path(discussion), class: 'text--teal'
  - if discussion.posts.count > 3
    - more_posts_count = discussion.posts.count - 3
    = "(#{more_posts_count} more posts)"

app/views/supplements/_form.html.haml
= simple_form_for @supplement, url: community_supplements_path(@community) do |f|
  = f.input :title
  = f.input :description
  = f.input :link, as: :url, placeholder: 'ex. https://www.google.com'
  .modal-footer
    .btn.btn-default{ data: { dismiss: 'modal' } }
      = 'Close'
    = f.submit 'Add Resource', class: 'btn btn-primary'